name: CMIP6_data
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py311ha68e1ae_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - arrow-cpp=11.0.0=h57928b3_13_cpu
  - asciitree=0.3.3=py_2
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - aws-c-auth=0.6.26=h1262f0c_1
  - aws-c-cal=0.5.21=h7cda486_2
  - aws-c-common=0.8.14=hcfcfb64_0
  - aws-c-compression=0.2.16=h8a79959_5
  - aws-c-event-stream=0.2.20=h5f78564_4
  - aws-c-http=0.7.6=h2545be9_0
  - aws-c-io=0.13.19=h0d2781e_3
  - aws-c-mqtt=0.8.6=hd211e0c_12
  - aws-c-s3=0.2.7=h8113e7b_1
  - aws-c-sdkutils=0.1.8=h8a79959_0
  - aws-checksums=0.1.14=h8a79959_5
  - aws-crt-cpp=0.19.8=he6d3b81_12
  - aws-sdk-cpp=1.10.57=h64004b3_8
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - blosc=1.21.3=hdccc3a2_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost-cpp=1.78.0=h9f4b32c_3
  - bottleneck=1.3.7=py311h59ca53f_0
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py311ha68e1ae_1005
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.18.1=h8ffe710_0
  - ca-certificates=2022.12.7=h5b45459_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cairo=1.16.0=hd694305_1014
  - cartopy=0.21.1=py311h178a126_1
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cf_xarray=0.8.0=pyhd8ed1ab_0
  - cffi=1.15.1=py311h7d9ee11_3
  - cfitsio=4.2.0=h9ebe7e4_0
  - cftime=1.6.2=py311h59ca53f_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - cmocean=3.0.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.7=py311h005e61a_0
  - cryptography=40.0.1=py311h28e9c30_0
  - curl=8.0.1=h68f0423_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py311ha68e1ae_1
  - dask=2023.3.2=pyhd8ed1ab_0
  - dask-core=2023.3.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2023.3.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h63175ca_1
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fastprogress=1.0.3=pyhd8ed1ab_0
  - fiona=1.9.3=py311ha4db88c_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.3=py311ha68e1ae_0
  - freetype=2.12.1=h546665d_1
  - freexl=1.0.6=h67ca5e6_1
  - frozenlist=1.3.3=py311ha68e1ae_0
  - fsspec=2023.4.0=pyh1a96a4e_0
  - gcsfs=2023.4.0=pyhd8ed1ab_0
  - gdal=3.6.3=py311h4bd9738_1
  - geopandas=0.12.2=pyhd8ed1ab_0
  - geopandas-base=0.12.2=pyha770c72_0
  - geos=3.11.2=h1537add_0
  - geotiff=1.7.1=hb4c6682_7
  - gettext=0.21.1=h5728263_0
  - gflags=2.2.2=ha925a31_1004
  - glib=2.74.1=h12be248_1
  - glib-tools=2.74.1=h12be248_1
  - glog=0.6.0=h4797de2_0
  - google-api-core=2.11.0=pyhd8ed1ab_0
  - google-auth=2.17.3=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_0
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-storage=2.8.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py311h48d9ab2_4
  - google-resumable-media=2.4.1=pyhd8ed1ab_0
  - googleapis-common-protos=1.57.1=pyhd8ed1ab_0
  - grpcio=1.52.1=py311h5f90226_1
  - gst-plugins-base=1.22.0=h001b923_2
  - gstreamer=1.22.0=h6b5321d_2
  - hdf4=4.2.15=h1334946_6
  - hdf5=1.12.2=nompi_h57737ce_101
  - heapdict=1.0.1=py_0
  - icu=70.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.3.0=pyha770c72_0
  - importlib_metadata=6.3.0=hd8ed1ab_0
  - intake=0.6.8=pyhd8ed1ab_0
  - intake-esm=2022.9.18=pyhd8ed1ab_0
  - intel-openmp=2023.0.0=h57928b3_25922
  - ipykernel=6.22.0=pyh025b116_0
  - ipython=8.12.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h1ea47a8_0
  - kealib=1.5.0=h61be68b_0
  - kiwisolver=1.4.4=py311h005e61a_1
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libabseil=20230125.0=cxx17_h63175ca_1
  - libaec=1.0.6=h63175ca_1
  - libarrow=11.0.0=h04c43f8_13_cpu
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libclang=15.0.7=default_h77d9078_1
  - libclang13=15.0.7=default_h77d9078_1
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.0.1=h68f0423_0
  - libdeflate=1.17=hcfcfb64_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.6.3=hd256549_1
  - libglib=2.74.1=he8f3873_1
  - libgoogle-cloud=2.8.0=hf2ff781_1
  - libgrpc=1.52.1=h32da247_1
  - libhwloc=2.9.0=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=16_win64_mkl
  - libnetcdf=4.9.1=nompi_h83fa41b_102
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libpq=15.2=ha9684e8_0
  - libprotobuf=3.21.12=h12be248_0
  - librttopo=1.1.0=he1da8c1_13
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=h2bb424f_24
  - libsqlite=3.40.0=hcfcfb64_0
  - libssh2=1.10.0=h9a1e1f7_3
  - libthrift=0.18.1=h9ce19ad_0
  - libtiff=4.5.0=hc3b8658_5
  - libutf8proc=2.8.0=h82a8f57_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.4=hc3477c8_0
  - libzip=1.9.2=h519de47_1
  - libzlib=1.2.13=hcfcfb64_4
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py311haddf500_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.2=py311ha68e1ae_0
  - matplotlib=3.7.1=py311h1ea47a8_0
  - matplotlib-base=3.7.1=py311h6e989c2_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - msgpack-python=1.0.5=py311h005e61a_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4=py311ha68e1ae_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf4=1.6.3=nompi_py311hd70422a_100
  - networkx=3.1=pyhd8ed1ab_0
  - numcodecs=0.11.0=py311h12c1d0e_1
  - numpy=1.24.2=py311h0b4df5a_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.0=hcfcfb64_0
  - orc=1.8.3=hada7b9e_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.5.3=py311hf63dbb6_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.0=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py311hc67b2de_0
  - pint=0.20.1=pyhd8ed1ab_0
  - pint-xarray=0.3=pyhd8ed1ab_0
  - pip=23.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.03.0=h934c637_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.2=hd87cd2b_0
  - proj=9.1.1=heca977f_2
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - protobuf=4.21.12=py311h12c1d0e_0
  - psutil=5.9.4=py311ha68e1ae_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=11.0.0=py311h6a6099b_13_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.7=py311ha68e1ae_0
  - pygeos=0.14=py311h343093d_1
  - pygments=2.15.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.5.0=py311h36482e4_0
  - pyqt=5.15.7=py311h125bc19_3
  - pyqt5-sip=12.11.0=py311h12c1d0e_3
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.11.3=h2628c8c_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywin32=304=py311h12c1d0e_2
  - pyyaml=6.0=py311ha68e1ae_5
  - pyzmq=25.0.2=py311h7b3f143_0
  - qt-main=5.15.8=h88fe7eb_7
  - rasterio=1.3.6=py311hc06ee40_0
  - re2=2023.02.02=h63175ca_0
  - regionmask=0.9.0=pyhd8ed1ab_0
  - requests=2.28.2=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - rtree=1.0.1=py311hcacb13a_1
  - scikit-learn=1.2.2=py311h142b183_1
  - scipy=1.10.1=py311h37ff6ca_0
  - setuptools=67.6.1=pyhd8ed1ab_0
  - shapely=2.0.1=py311h343093d_1
  - sip=6.7.8=py311h12c1d0e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.40.0=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=h91493d7_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.13.2=h3132609_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py311ha68e1ae_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vc=14.3=hb6edc58_10
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xarray=2023.3.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=h63175ca_2
  - xmip=0.7.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2023.2.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.8.2=py311ha68e1ae_0
  - zarr=2.14.2=pyhd8ed1ab_0
  - zeromq=4.3.4=h0e60522_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h12be248_6
prefix: C:\Users\ldfierro\AppData\Local\miniconda3\envs\CMIP6_data
